context:
  name: "pylha"
  version: "0.4"
  python_min: "3.7"

package:
  name: ${{ name|lower }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/pylha-${{ version }}.tar.gz
  sha256: 911f9ff81343a28675933076f96026d2b8a53dbc0aabb953440ca56339c908cf

build:
  noarch: python
  script: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python ${{ python_min }}.*
    - setuptools
    - pip
  run:
    - python >=${{ python_min }}
    - pyyaml

tests:
  - python:
      imports:
        - pylha
      pip_check: true
      python_version: ${{ python_min }}.*

about:
  homepage: https://github.com/DavidMStraub/pylha
  summary: A Python package to convert data files in SLHA and similar formats to Python objects, JSON, or YAML.
  license: MIT
  license_file: LICENSE
  repository: https://github.com/DavidMStraub/pylha

extra:
  recipe-maintainers:
    - matthewfeickert
